project_name: vumm
before:
  hooks:
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - 386
      - amd64
    ldflags:
      - -s -w -X github.com/vumm/cli/internal/common.version={{.Version}} -X github.com/vumm/cli/internal/common.commit={{.ShortCommit}} -X github.com/vumm/cli/internal/common.date={{ .CommitDate }}
archives:
  - name_template: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}'
    format_overrides:
      - goos: windows
        format: zip
    files:
      - README.md
      - LICENSE
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^cicd:'
      - '^refactor'
      - Merge pull request
      - Merge branch
