[package]
name = "vumm_installer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
semver = "1.0.17"
tokio = { version = "1.28.0", features = ["full"] }
vumm_api = { path = "../vumm_api" }
