name: goreleaser

on:
  push:
    tags:
      - '*'

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      # ubuntu is missing wixl https://github.com/actions/virtual-environments/issues/3857
      - name: Install msitools (wixl)
        run: sudo apt update -qq && sudo apt install -qq -y wixl

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and publish msi installers
        run: |  # manually until https://github.com/goreleaser/goreleaser/issues/1295
          tag="${GITHUB_REF#refs/tags/}"
          version=${tag#v}
          VERSION=${version} make msi
          msi_86=dist/vumm_${version}_windows_386.msi
          msi_64=dist/vumm_${version}_windows_amd64.msi
          mv dist/vumm_windows_386/vumm.msi ${msi_86}
          mv dist/vumm_windows_amd64/vumm.msi ${msi_64}
          gh release upload "${tag}" "${msi_86}" "${msi_64}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}