name: goreleaser

on:
  push:
    tags:
      - '*'

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload windows dist artifact
        uses: actions/upload-artifact@v2
        with:
          name: windows-dist
          retention-days: 1
          path: |
            dist/vumm_windows_386
            dist/vumm_windows_amd64

  msi:
    needs: goreleaser
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Download windows dist artifact
        uses: actions/download-artifact@v2
        with:
          name: windows-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Set path for candle and light
        shell: bash
        run: echo "C:\Program Files (x86)\WiX Toolset v3.11\bin" >> $GITHUB_PATH

      - name: Unzip exe's
        shell: bash
        run: |
          cd dist
          cd vumm_windows_386
          unzip -o *.zip && rm -v *.zip
          cd ../vumm_windows_amd64
          unzip -o *.zip && rm -v *.zip

      - name: Build and publish msi installers
        shell: bash
        run: |  # manually until https://github.com/goreleaser/goreleaser/issues/1295
          tag="${GITHUB_REF#refs/tags/}"
          version=${tag#v}
          VERSION=${version} make msi
          msi_86=dist/vumm_${version}_windows_386.msi
          msi_64=dist/vumm_${version}_windows_amd64.msi
          mv dist/vumm_windows_386/vumm.msi ${msi_86}
          mv dist/vumm_windows_amd64/vumm.msi ${msi_64}
          gh release upload "${tag}" "${msi_86}" "${msi_64}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}